Meezzi/mongbi-app

- pubspec.lock
pubspec.lock web 중복 수정
- LoginPage UI 레이아웃 구현
Closes #22
> [Core] pubspec.lock 오류 수정

- lib/core/background_music_player.dart
- lib/presentation/splash/splash_page.dart
애니메이션 속도 조정
애니메이션 속도 조정
Closes #48
> [Splash]애니메이션 속도 조정

- lib/presentation/common/floating_animation_widget.dart
- lib/presentation/home/home_page.dart
- lib/presentation/splash/splash_page.dart
- 몽비 애니메이션 공통 위젯으로 분리
- 홈 화면 몽비 떠다니는 애니메이션 구현
- SplashPage의 몽비 애니메이션을 공통 위젯으로 분리
- 홈 화면에 몽비 떠다니는 애니메이션 구현
Closes #54
> [Home] 몽비 애니메이션

- lib/presentation/auth/social_login_page.dart
바텀시트 외부 영역 터치시 바텀 시트 내려가는 현상 수정
바텀시트 외부 영역 터치시 바텀 시트 내려가는 현상 수정
Closes #75
> [Terms] 바텀시트 외부 영역 터치시 바텀 시트 내려가는 현상 수정

- lib/core/router.dart
- lib/main.dart
- lib/presentation/auth/viewmodels/auth_view_model.dart
- lib/presentation/setting/profile_setting_page.dart
- lib/presentation/setting/widgets/logout_confirm_dialog.dart
네이버& 카카오 로그아웃 기능 구현 완료
네이버& 카카오 로그아웃 기능 구현 완료
Closes #12
> [Auth] 네이버& 카카오 로그아웃 기능 구현 완료

- lib/core/router.dart
- lib/presentation/remind/remind_time_time_setting_page.dart
- lib/presentation/setting/nickname_input_page.dart
> [Core] 라우팅 수정

- lib/presentation/onboarding/widgets/onbording_skip_button_widget.dart
몽비 만나러 가기 버튼 잘리는 현상 수정
몽비 만나러 가기 버튼 잘리는 현상 수정
Closes #102
> [Onbording] 몽비 만나러 가기 버튼 잘리는 현상 수정

- lib/core/route_observer.dart
- lib/core/router.dart
- lib/data/dtos/statistics_dto.dart
- lib/data/repositories/remote_statistics_repository.dart
- lib/presentation/statistics/statistics_page.dart
- lib/presentation/statistics/widgets/custom_snack_bar.dart
- lib/presentation/statistics/widgets/month_statistics.dart
- lib/presentation/statistics/widgets/month_year_picker.dart
- lib/presentation/statistics/widgets/mood_state_info_modal.dart
- lib/presentation/statistics/widgets/year_statistics.dart
꿈 작성 페이지로 유도하는 스낵바 표시 상황 변경
- 현재년도와 현재 월인 경우에만 스낵바 표시하기로 변경하기
- 미래 시점의 월을 disable 처리
Closes #96
> [Statistics] 꿈 작성 페이지로 유도하는 스낵바 표시 조건 변경

- lib/data/data_sources/alarm_data_source.dart
- lib/data/data_sources/remote_alarm_data_source.dart
- lib/data/dtos/alarm_dto.dart
- lib/data/repositories/remote_alarm_repository.dart
- lib/domain/entities/alarm.dart
- lib/domain/repositories/alarm_repository.dart
- test/data/alarm_data_source_test.dart
- test/data/alarm_repository_test.dart
알림 페이지 TDD 작성
- 데이터 소스, 리포지토리 TDD 작성
Closes #8
> [Alarm] 알림 페이지 TDD 작성

- lib/presentation/common/filled_button_widget.dart
- lib/presentation/common/ghost_button_widget.dart
공통 버튼 - 폰트 미적용 오류 해결
- 클래스 사용하지 않고 직접 스타일 적용하여 해결
Closes #135
> [Core] 공통 버튼 - 폰트 미적용 오류 해결

- lib/core/main_scaffold.dart
- lib/presentation/setting/alarm_setting_page.dart
- lib/presentation/setting/widgets/setting_rounded_list_tile_item.dart
- lib/presentation/setting/widgets/setting_toggle_switch.dart
- lib/presentation/setting/widgets/setting_user_info_header.dart
- 설정 화면 백그라운드 색상 수정
- 배경음악 토글 패딩 설정
- 상단 화살표 위치 수정
- 알림 설정 화면에서 선택시 InkWell 제거
- 설정 화면 백그라운드 색상 수정
- 배경음악 토글 패딩 설정
- 상단 화살표 위치 수정
- 알림 설정 화면에서 선택시 InkWell 제거
Closes #139
> [Setting] QA 피드백 적용 - UI 변경

- .gitignore
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- pubspec.lock
- pubspec.yaml
- 앱 id 변경
- Firebase core 추가
- 앱 id 변경
- Firebase core 추가
Closes #141
> [Core] 앱 id 변경

- ios/Podfile.lock
- lib/core/main_scaffold.dart
- lib/core/no_transition_page.dart
- lib/core/router.dart
- 하단 + 버튼 그림자 적용
- 타이틀 좌측 정렬
- 화면 이동 애니메이션 적용 X
- 하단 + 버튼 그림자 적용
- 타이틀 좌측 정렬
- 홈, 기록, 통계, 설정 화면에서 화면 이동 애니메이션 제거
Closes #154
> [Home] QA 피드백 적용 - UI 변경

- lib/core/date_formatter.dart
- lib/core/main_scaffold.dart
- lib/data/data_sources/alarm_data_source.dart
- lib/data/data_sources/remote_alarm_data_source.dart
- lib/data/dtos/alarm_dto.dart
- lib/data/repositories/remote_alarm_repository.dart
- lib/domain/entities/alarm.dart
- lib/domain/repositories/alarm_repository.dart
- lib/domain/use_cases/fetch_alarms_use_case.dart
- lib/domain/use_cases/update_confirm_status_use_case.dart
- lib/domain/use_cases/update_is_read_status_use_case.dart
- lib/presentation/alarm/alarm_page.dart
- lib/presentation/alarm/models/alarm_model.dart
- lib/presentation/alarm/view_models/alarm_view_model.dart
- lib/presentation/alarm/widgets/alarm_app_bar.dart
- lib/presentation/alarm/widgets/alarm_body.dart
- lib/presentation/alarm/widgets/alarm_item.dart
- lib/presentation/alarm/widgets/alarm_type.dart
- lib/presentation/alarm/widgets/delete_modal.dart
- lib/providers/alarm_provider.dart
- test/data/alarm_data_source_test.dart
- test/data/alarm_repository_test.dart
[Alarm] 알림 API 연동
- QA 후 UI 변경
- API 연동 및 데이터로 UI 변경
Closes #153
> [Alarm] 알림 API 연동

- ios/Podfile.lock
- lib/core/calculate_time_remaining.dart
- pubspec.lock
- 홈 화면에서 챌린지 마감 시간이 -인 오류 수정
- 챌린지 시간 수정
Closes #169
> [Challenge] 챌린지 마감 시간 오류

- ios/Podfile.lock
- lib/core/calculate_time_remaining.dart
- lib/presentation/auth/social_login_page.dart
- pubspec.lock
]Apple로그인 버튼은 Android에서 안보이게 수정
]Apple로그인 버튼은 Android에서 안보이게 수정
Closes #170
> [Auth]Apple로그인 버튼은 Android에서 안보이게 수정

- lib/data/dtos/history_dto.dart
- lib/data/repositories/remote_history_repository.dart
- lib/domain/entities/history.dart
- lib/presentation/history/widgets/history_item.dart
- lib/presentation/history/widgets/history_notice.dart
기록에 챌린지 띄우기
- DTO, Entity 변경
- 챌린지 UI 추가
Closes #172
> [History] 기록에 챌린지 띄우기

- lib/presentation/remind/remind_time_time_setting_page.dart
- lib/presentation/remind/view_model/remind_time_setting_view_model.dart
- lib/presentation/setting/alarm_setting_page.dart
- lib/presentation/setting/view_models/alarm_setting_view_model.dart
리마인드 토글 동기화 작업
리마인드 토글 동기화 작업
Closes #177
> [Setting] 리마인드 토글 동기화 작업

- lib/presentation/dream/dream_interpretation_page.dart
- title 좌측 정렬
- 자동 생성 leading 아이콘 제거
- title 좌측 정렬
- 자동 생성 leading 아이콘 제거
Closes #194
> [Dream] QA 피드백 적용 - UI 변경

- lib/core/main_navi_tab_bar.dart
- lib/core/main_scaffold.dart
- lib/core/set_up_fcm.dart
- lib/presentation/statistics/widgets/month_statistics.dart
알림 아이콘, 페이지 숨김 처리
- 알림 아이콘, 페이지 숨김 처리(주석)
Closes #197
> [Alarm] 알림 아이콘, 페이지 숨김 처리

- lib/data/data_sources/remote_apple_auth_data_source.dart
애플로그인 실패 현상 해결
애플로그인 실패 현상 해결
Closes #184
> [Auth] 애플로그인 실패 현상 해결

- lib/presentation/dream/dream_interpretation_page.dart
- lib/presentation/setting/nickname_input_page.dart
- 닉네임 설정 화면에서 leading 아이콘이 두 개 나타나는 오류 수정
- 닉네임 설정 화면에서 leading 아이콘이 두 개 나타나는 오류 수정
Closes #200
> [Setting] 닉네임 설정 leading 이 두 개 나타나는 오류

- lib/presentation/remind/remind_time_setting_page.dart
- lib/presentation/remind/remind_time_time_setting_page.dart
리딩 버튼 위치 수정
- 리마인드 소개 페이지, 리마인드 설정 페이지의 리딩 버튼 위치 동일하게 수정
Closes #202
> style: 리딩 버튼 위치 수정

- lib/presentation/auth/viewmodels/auth_view_model.dart
- lib/presentation/setting/widgets/logout_account_modal.dart
애플 로그인 로그아웃 기능 추가
애플 로그인 로그아웃 기능 추가
Closes #212 2
> [Auth] 애플 로그인 로그아웃 기능 추가

- lib/core/exceptions/auth_custom_exception.dart
- lib/data/data_sources/remote_apple_auth_data_source.dart
- lib/data/data_sources/remote_kakao_auth_data_source.dart
- lib/data/data_sources/remote_naver_auth_data_source.dart
- lib/presentation/auth/social_login_page.dart
- lib/presentation/auth/viewmodels/auth_view_model.dart
- 예외에 따른 스낵바 표시
- 로그인 관련 커스텀 예외 클래스 생성
- DataSource, ViewModel에서 Custom 예외 던지기
- SocialLoginPage에서 예외 메세지에 따른 스낵바 표시
Closes #214
> [Auth] 로그인 예외 처리

- lib/domain/use_cases/login_with_apple.dart
- lib/presentation/auth/viewmodels/auth_view_model.dart
애플로그인 정보 못받아오는 버그 수정
애플로그인 정보 못받아오는 버그 수정
Closes #223
> [Auth]애플로그인 정보 못받아오는 버그 수정

- ios/Flutter/Release.xcconfig
- ios/Runner/Info.plist
- ios/Runner/Runner.entitlements
- Univarsal Link 추가
- 카카오 로그인 안되는 오류 수정
> [Core] Univarsal Link 추가

- lib/presentation/history/widgets/calendar_bottom_sheet.dart
- lib/presentation/history/widgets/calendar_bottom_sheet_month_selector.dart
- lib/presentation/history/widgets/calendar_bottom_sheet_year_selector.dart
- lib/presentation/history/widgets/calendar_change_button.dart
- lib/presentation/history/widgets/history_app_bar.dart
getResponsiveByWidth 제거
- 반응형 고려로 사용한 함수 제거
Closes #252
> [History] getResponsiveByWidth 제거

- lib/presentation/remind/view_model/remind_time_setting_view_model.dart
리마인드 푸시 알림 문구 수정
리마인드 푸시 알림 문구 수정
Closes #256
> [Remind] 리마인드 푸시 알림 문구 수정

- lib/presentation/setting/setting_page.dart
고겍센터 버튼 위치 변경
고겍센터 버튼 위치 변경
Closes #274
> [Setting] 고겍센터 버튼 위치 변경

- lib/presentation/remind/remind_time_setting_page.dart
- lib/presentation/setting/nickname_input_page.dart
네비게이션 방식 수정 - 홈으로 돌아가기 및 닉네임 입력 페이지에서 알림 설정 페이지로의 이동 방식 변경
네비게이션 방식 수정 - 홈으로 돌아가기 및 닉네임 입력 페이지에서 알림 설정 페이지로의 이동 방식 변경
Closes #278
> [Setting] 네비게이션 방식 수정 - 홈으로 돌아가기 및 닉네임 입력 페이지에서 알림 설정 페이지로의 이동 방식 변경

- lib/presentation/setting/alarm_setting_page.dart
알림 권한 요청 및 상태 관리 개선
알림 권한 요청 및 상태 관리 개선
Closes #281
> [Setting]알림 권한 요청 및 상태 관리 개선

- lib/presentation/remind/view_model/remind_time_setting_view_model.dart
알림 권한 요청 설정을 활성화하여 사용자 경험 개선
알림 권한 요청 설정을 활성화하여 사용자 경험 개선
Closes #283
> [Setting]알림 권한 요청 설정을 활성화하여 사용자 경험 개선

- lib/presentation/remind/remind_time_time_setting_page.dart
- lib/presentation/remind/view_model/remind_time_setting_view_model.dart
- lib/presentation/setting/alarm_setting_page.dart
알림 권한 요청 로직 개선 및 Firebase Analytics 이벤트 제거
알림 권한 요청 로직 개선 및 Firebase Analytics 이벤트 제거
Closes #285
> [Setting] 알림 권한 요청 로직 개선 및 Firebase Analytics 이벤트 제거

- ios/Runner/Info.plist
> [Core] iPad 지원 비활성화
